/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446xx.h"
#include "stm32f446xx_gpio_driver.h"


#define HIGH 1
#define LOW 0
#define BTN_PRESSED LOW

void delay_250ms(void)
{
    for (volatile uint32_t j = 0; j < 400000; j++);
}

int main(void)
{

	GPIO_Handle_t GpioLed;
	GPIO_Handle_t extLED1, extLED2;
	GPIO_Handle_t button;

	//==================== PA5 LED ====================
	GpioLed.pGPIOx = GPIOA;
	GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5;
	GpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
	GpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_PeriClockControl(GPIOA,ENABLE);
	GPIO_Init(&GpioLed);

	//==================== PA6 LED ====================
	extLED1.pGPIOx = GPIOA;
	extLED1.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_6;
	extLED1.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	extLED1.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
	extLED1.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	extLED1.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_Init(&extLED1);

	//==================== PA7 LED ====================
	extLED2.pGPIOx = GPIOA;
	extLED2.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_7;
	extLED2.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	extLED2.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
	extLED2.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	extLED2.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_Init(&extLED2);

	//==================== BUTTON PC13 INTERRUPT ====================
	button.pGPIOx = GPIOC;
	button.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	button.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_FT;   // Falling edge interrupt
	button.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
	button.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_PeriClockControl(GPIOC, ENABLE);
	GPIO_Init(&button);

	// Enable interrupt in NVIC
	GPIO_IRQPriorityConfig(IRQ_NO_EXTI15_10, NVIC_IRQ_PRI15);
	GPIO_IRQInterruptConfig(IRQ_NO_EXTI15_10, ENABLE);


	//==================== MAIN LOOP ====================
	while(1)
	{
		GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_6, HIGH);
		GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_7, LOW);
		delay_250ms();

		GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_6, LOW);
		GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_7, HIGH);
		delay_250ms();
	}

	return 0;
}

void EXTI15_10_IRQHandler(void)
{
	GPIO_IRQHandling(GPIO_PIN_NO_13);   // clear pending bit

	GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_NO_5);  // toggle PA5 LED
}
