/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446xx.h"
#include "stm32f446xx_gpio_driver.h"

// macros
#define HIGH 		1
#define LOW 		0
#define BUTTON 		GPIO_PIN_NO_13
#define Blink_LED 	GPIO_PIN_NO_5
#define LED1 		GPIO_PIN_NO_6
#define LED2		GPIO_PIN_NO_7


void delay(void)
	{
    	for (uint32_t i=0; i<400000; i++);
	}

int main(void)
{
	// handle declaration
	GPIO_Handle_t GpioLed;
	GPIO_Handle_t extLED1, extLED2;
	GPIO_Handle_t button;

	//PA5 led configuration
 	GpioLed.pGPIOx = GPIOA;
	GpioLed.GPIO_PinConfig.GPIO_PinNumber = Blink_LED;
	GpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	// PA6 led configuration
	extLED1.pGPIOx=GPIOA;
	extLED1.GPIO_PinConfig.GPIO_PinNumber = LED1;
	extLED1.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	extLED1.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	extLED1.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	extLED1.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	// PA7 led configuration
	extLED2.pGPIOx=GPIOA;
	extLED2.GPIO_PinConfig.GPIO_PinNumber = LED2;
	extLED2.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	extLED2.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
	extLED2.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	extLED2.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	// button configuration
	button.pGPIOx = GPIOC;
	button.GPIO_PinConfig.GPIO_PinNumber = BUTTON;
	button.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;

	// clock enabling
	GPIO_PeriClockControl(GPIOA,ENABLE); // leds port a clock enabling
	GPIO_PeriClockControl(GPIOC, ENABLE); // button port c clock enabling

	// handles initialization
	GPIO_Init(&GpioLed);
	GPIO_Init(&extLED1);
	GPIO_Init(&extLED2);
	GPIO_Init(&button);

	while(1)
	{

		if(GPIO_ReadFromInputPin(GPIOC, BUTTON)==0)
		{
			delay();
			while(GPIO_ReadFromInputPin(GPIOC, BUTTON)==0);
			GPIO_ToggleOutputPin(GPIOA, Blink_LED);
		}
		// external LEDs toggling every time without button press actions
			GPIO_WriteToOutputPin(GPIOA, LED1, HIGH); // external led 1 ON
			GPIO_WriteToOutputPin(GPIOA, LED2, LOW);  // external led 2 OFF
			delay();
			GPIO_WriteToOutputPin(GPIOA, LED1, LOW);  // external led 1 OFF
			GPIO_WriteToOutputPin(GPIOA, LED2, HIGH);  // external led 2 ON
			delay();

	}
}
