/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************

 this program will read the real time atmospheric temperature
 written  by Anees Kokadan
 */

#include <stdint.h>
#include "stm32_f446xx.h"
#include<stdio.h>

void ADC_init(void)
{
	RCC->AHB1ENR|=(1<<0);
	GPIOA->MODER|=(0X3<<0); // PA0 set as 11, for analog mode
	GPIOA->PUPDR&=~(0X3<<0); // No pull up, pull down

	RCC->APB2ENR|=(1<<8);  // ADC1 Clock enable

	/*
	 * ADC_SR = ADC status register
	 * OVR STRT JSTRT JEOC EOC AWD
	 * its all values are set by hardware, we do not need to set it manually
	 * instead we will check its value during program running
	 * like, to check if the conversion finished or not (EOC bit )
	 * if EOC is 0 -> conversion not completed
	 * if EOC is 1 -> conversion completed
	 */

	// ADC configuration
	ADC1->CR2=0;	//clearing CR2 register
	ADC1->SQR3=0;// clearing SQR3 register
	ADC1->SMPR2|=(0X3<<0); // SAMPLING 56 cycles for channel 0 --> PA0

	/*
	 * for LM35, to reduce noise the sampling time need to set to 56
	 * from reference manual of stm32, I found that for 56 cycles we need to set 0x3 on channel 0
	 */

	ADC1->CR2|=(1<<0);  // ADC ON, inside CR2 register 0th bit is ADON
	/*
	 * Bit 0 ADON: A/D Converter ON / OFF
	This bit is set and cleared by software.
	0: Disable ADC conversion and go to power down mode
	1: Enable ADC -- > here we made it 1 to make ADC ON
	 */
}

uint16_t ADC_Read(void)
{
	ADC1->CR2|=(1<<30);			// SWSTART --> Start conversion of regular channels
	while (!(ADC1->SR&(1<<1)));	// wait until EOC is set to 1 (wait until conversion complete)
	// EOC is the 1st bit of SR register
	return ADC1->DR;				// take the value from data register
	/*
	 * DR --> These bits are read-only. They contain the conversion result from the regular
	channels.
	 */
}


int main(void)
{
    uint16_t adc;
    float voltage, temperature;

    ADC_init();

    while(1)
    {
    	adc=ADC_Read();
    	voltage=(adc * 3.3f) / 4095.0f;
    	temperature=voltage * 100.0f;
    	printf("Room temperature: %.2f C\n", temperature);
    	for(volatile int i=0; i<200000; i++); // small delay

    }

}


