/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f446xx.h"
#include "stm32f446xx_gpio_driver.h"
#include "stm32f446xx_i2c_driver.h"

I2C_Handle_t I2C1Handle;

void I2C1_GPIOInit(void)
{
    GPIO_Handle_t I2CPins;

    I2CPins.pGPIOx = GPIOB;

    I2CPins.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
    I2CPins.GPIO_PinConfig.GPIO_PinAltFunMode = 4;      // AF4 = I2C1
    I2CPins.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_OD;
    I2CPins.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PU;
    I2CPins.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;

    /* PB8 -> SCL */
    I2CPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_8;
    GPIO_Init(&I2CPins);

    /* PB9 -> SDA */
    I2CPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_9;
    GPIO_Init(&I2CPins);
}

void I2C1_Init_Config(void)
{
    I2C1Handle.pI2Cx = I2C1;

    I2C1Handle.I2C_Config.I2C_AckControl = I2C_ACK_ENABLE;
    I2C1Handle.I2C_Config.I2C_DeviceAddress = 0x61;
    I2C1Handle.I2C_Config.I2C_FMDutyCycle = I2C_FM_DUTY_2;
    I2C1Handle.I2C_Config.I2C_SCLSpeed = I2C_SCL_SPEED_SM;

    I2C_Init(&I2C1Handle);
}

void OLED_SendCommands(uint8_t *cmds, uint32_t len)
{
    I2C_MasterSendData(
            &I2C1Handle,
            cmds,
            len,
            0x3C,
            I2C_DISABLE_SR);
}

int main(void)
{
    I2C1_GPIOInit();
    I2C1_Init_Config();

    I2C_PeripheralControl(I2C1, ENABLE);

    uint8_t cmd[2];
    uint8_t data[129];

    while(1)
    {
        /* Page 0 */
        cmd[0] = 0x00;
        cmd[1] = 0xB0;
        I2C_MasterSendData(&I2C1Handle, cmd, 2, 0x3C, I2C_DISABLE_SR);

        cmd[1] = 0x00;
        I2C_MasterSendData(&I2C1Handle, cmd, 2, 0x3C, I2C_DISABLE_SR);

        cmd[1] = 0x10;
        I2C_MasterSendData(&I2C1Handle, cmd, 2, 0x3C, I2C_DISABLE_SR);

        data[0] = 0x40;

        for(int i=1;i<129;i++)
        {
            data[i] = 0xFF;
        }

        I2C_MasterSendData(&I2C1Handle,
                           data,
                           129,
                           0x3C,
                           I2C_DISABLE_SR);

        while(1);
    }
}
