/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32_f446xx.h"

#define LED_PIN         5

void delay_ms(uint32_t ms) // delay function
{
    volatile uint32_t count;

    while(ms--)
    {

        for(count = 0; count < 4000; count++)
        {
        		// empty loop, just for delay
        }
    }

}


int main(void)
{
	GPIOA_CLK_EN(); // Enable GPIOA clock
	GPIOA->MODER &= ~(0x3 << (LED_PIN*2)); // PA5 set to 00
	GPIOA->MODER|= (1<<(LED_PIN*2)); // PA5 set to 01, which is 01: General purpose output mode
	GPIOA->OTYPER &= ~(1<<LED_PIN); // output type set to push pull state
	GPIOA->OSPEEDR &=~ (0x3<<(LED_PIN*2)); // 5th bit set to 0
	GPIOA->OSPEEDR|= (1<<(LED_PIN*2)); // 5th bit set to 01, for medium speed
	GPIOA->PUPDR &= ~(0x3 << (LED_PIN*2)); // 5th bit set to 00, means no pull up and  pull down
	GPIOA->ODR&=~(1<<LED_PIN); // to set PA5 to 0

    while(1)
    {
       GPIOA->ODR ^= (1 << 5);   // Toggle LED using XOR
       delay_ms(500);            // 500 ms delay
    }
}

